version: '3.7'
services:
  php-fpm56: # 只用php-fpm72可以删除php-fpm56
    build: ./php56
    container_name: "canren-lnmp-php56"
    ports:
      - "9001:9000"
    networks:
      - "lnmp"
    volumes:
      - ../../../dockerapps:/data/www:rw
      - ./php56/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./php56/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ../logs/php-fpm56:/var/log/php-fpm:rw
    restart: always
    command: php-fpm

  php-fpm72:
    build: ./php72
    container_name: "canren-lnmp-php72"
    ports:
      - "9000:9000"
    networks:
      - "lnmp"
    volumes:
      - ../../../dockerapps:/data/www:rw
      - ./php72/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./php72/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ../logs/php-fpm72:/var/log/php-fpm:rw
    restart: always
    command: php-fpm

  nginx:
    build: ./nginx
    container_name: "canren-lnmp-nginx"
    ports:
      - "80:80"
    depends_on:
      - php-fpm72
    networks:
      - "lnmp"
    volumes:
      - ../../../dockerapps:/data/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/var/log/nginx:rw
    restart: always
    command: nginx -g 'daemon off;'

  mysql-db:
    build: ./mysql
    container_name: "canren-lnmp-mysql"
    ports:
      - "3306:3306"
    networks:
      - "lnmp"
    volumes:
      - ../data/mysql:/var/lib/mysql:rw
      - ../logs/mysql:/var/lib/mysql-logs:rw
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    restart: always
    command: "--character-set-server=utf8"

  redis-db:
    build: ./redis
    container_name: "canren-lnmp-redis"
    ports:
      - "6379:6379"
    networks:
      - "lnmp"
    volumes:
      - ../data/redis:/data
    restart: always

  mongo-db:
    build: ./mongo
    container_name: "canren-lnmp-mongo"
    ports:
      - "27017:27017"
    networks:
      - "lnmp"
    volumes:
      - ../data/mongo:/data:rw
      - ../logs/mongo:/var/log/mongodb:rw
      - ./mongo/mongod.conf:/etc/mongod.conf:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: always

  memcached:
    build: ./memcached
    container_name: "canren-lnmp-memcached"
    ports:
      - "11211:11211"
    networks:
      - "lnmp"
    command: "-m 128"
    restart: always

networks:
  lnmp:
    driver: bridge