version: '3.4'
services:

  php-fpm72:
    build:
      context: php72/
      args:
        LNMP_PHP72_VERSION: $LNMP_PHP72_VERSION
    container_name: "canren-lnmp-php72"
    # privileged: true
    ports:
      - "9000:9000"
    networks:
      - "lnmp"
    volumes:
      - $WORKSPACES
      - ./php72/php.ini:/usr/local/etc/php/php.ini:rw
      - ./php72/php-fpm.conf:/usr/local/etc/php-fpm.conf:rw
      - ./php72/php-fpm.d:/usr/local/etc/php-fpm.d:cached
      - ./php72/worker/supervisor:/etc/supervisor:cached
      - ../logs/php-fpm72:/var/log/php-fpm:cached
    restart: always
    command: 
      - /bin/sh
      - -c
      - |
        /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
        /usr/local/sbin/php-fpm
  
  openresty:
    build:
      context: openresty/
      args:
        LNMP_OPENRESTY_VERSION: $LNMP_OPENRESTY_VERSION
    container_name: "canren-lnmp-openresty"
    # privileged: true
    ports:
      - "80:80"
    networks:
      - "lnmp"
    links:
      - php-fpm72
    depends_on:
      - php-fpm72
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:rw
      - ./openresty/conf.d:/etc/nginx/conf.d:cached
      - ../logs/openresty:/usr/local/openresty/nginx/logs:cached
    restart: always

  mysql-db:
    build:
      context: mysql/
      args:
        LNMP_MYSQL_VERSION: $LNMP_MYSQL_VERSION
    container_name: "canren-lnmp-mysql"
    ports:
      - "3306:3306"
    networks:
      - "lnmp"
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf:rw
      - ../data/mysql:/var/lib/mysql:cached
      - ../logs/mysql:/var/lib/mysql-logs:cached
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    restart: always
    command: "--character-set-server=utf8"

  redis-db:
    build:
      context: redis/
      args:
        REDIS_VERSION: $REDIS_VERSION
    container_name: "canren-lnmp-redis"
    ports:
      - "6379:6379"
    networks:
      - "lnmp"
    volumes:
      - ./redis/redis.conf:/etc/redis.conf:rw
      - ../data/redis:/data:cached
    command: "/etc/redis.conf"
    restart: always

  neo4j-db: # 默认密码是neo4j
    build:
      context: neo4j/
      args:
        NEO4J_VERSION: $NEO4J_VERSION
    container_name: "canren-lnmp-neo4j"
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - "lnmp"
    volumes:
      - ./neo4j/conf:/var/lib/neo4j/conf:rw
      - ../data/neo4j:/data:cached
      - ../logs/neo4j:/logs:cached
    restart: always

networks:
  lnmp:
    driver: bridge