version: '3.4'
services:

  php-fpm56:
    build:
      context: php56/
    container_name: "lnmp-php56"
    # privileged: true
    networks:
      - "lnmp"
    volumes:
      - $WORKSPACES
    restart: always
    command: /usr/local/sbin/php-fpm

  php-fpm71:
    build:
      context: php71/
    container_name: "lnmp-php71"
    # privileged: true
    networks:
      - "lnmp"
    volumes:
      - $WORKSPACES
    restart: always
    command: /usr/local/sbin/php-fpm

  php-fpm72:
    build:
      context: php72/
    container_name: "lnmp-php72"
    # privileged: true
    networks:
      - "lnmp"
    volumes:
      - $WORKSPACES
    restart: always
    command: /usr/local/sbin/php-fpm

  php-fpm74:
    build:
      context: php74/
    container_name: "lnmp-php74"
    # privileged: true
    networks:
      - "lnmp"
    volumes:
      - $WORKSPACES
    restart: always
    command: /usr/local/sbin/php-fpm

  openresty:
    build:
      context: openresty/
    container_name: "lnmp-openresty"
    # privileged: true
    ports:
      - "80:80"
      - "8080:8080"
      - "8088:8088"
    networks:
      - "lnmp"
    depends_on:
      - php-fpm56
      - php-fpm71
      - php-fpm72
    volumes:
      - $WORKSPACES
      - ./openresty/conf.d:/etc/nginx/conf.d:cached
      - ../logs/openresty:/usr/local/openresty/nginx/logs:cached
    restart: always

  mysql-db:
    build:
      context: mysql/
      args:
        LNMP_MYSQL_VERSION: $LNMP_MYSQL_VERSION
    container_name: "lnmp-mysql"
    ports:
      - "3306:3306"
    networks:
      - "lnmp"
    volumes:
      - ../data/mysql:/var/lib/mysql:cached
      - ../logs/mysql:/var/lib/mysql-logs:cached
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    restart: always
    command: "--character-set-server=utf8"

  redis-db:
    build:
      context: redis/
      args:
        REDIS_VERSION: $REDIS_VERSION
    container_name: "lnmp-redis"
    ports:
      - "6379:6379"
    networks:
      - "lnmp"
    volumes:
      - ./redis/redis.conf:/etc/redis.conf:rw
      - ../data/redis:/data:cached
    command: "/etc/redis.conf"
    restart: always

networks:
  lnmp:
    driver: bridge