version: '3.4'
services:

  sonarqube:
    build:
      context: sonarqube/
    container_name: "canren-sonarqube"
    ports:
      - "9001:9000"
    networks:
      - "sonarqube"
    volumes:
      - $WORKSPACES
    restart: always

networks:
  sonarqube:
    driver: bridge


  