version: '3.7'
services:
  gitlab:
    build:
      context: gitlab/
      args:
        GITLAB_VERSION: $GITLAB_VERSION
    container_name: "canren-gitlab"
    ports:
#      - "443:443"
      - "8081:80"
#      - "22:22"
    networks:
      - "gitlab"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ../logs/logs:/var/log/gitlab
      - ../data/data:/var/opt/gitlab
    restart: always

networks:
  gitlab:
    driver: bridge